name: Patrol_algorithm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: make file
        run: |
          cd ./Patrol_algorithm;
          autoreconf -ivf
          ls -l configure;
          chmod 775 configure;
          ./configure;
          make;
          ./Patrol_algorithm;
