name: sonar_Patrol_algorithm
on: [push]

jobs:
  sonarCloudTrigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: make and run
        run: |
          cd ./Patrol_algorithm;
          ls -l configure;
          chmod 775 configure;
          ./configure;
          make;
          ./Patrol_algorithm;
      - name: Patrol
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
