name: sonar_Patrol_algorithm
on: [push]

jobs:
  sonarCloudTrigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install C++ build wrapper
        run: |
          wget https://binaries.sonarsource.com/CommercialDistribution/sonar-cpp-plugin/build-wrapper-3.11.zip
          unzip build-wrapper-3.11.zip
          cd build-wrapper-3.11
          ls
      - name: make Patrol and run
        run: |
          cd ./Patrol_algorithm;
          autoreconf -ivf
          ls -l configure;
          chmod 775 configure;
          ./configure;
          make;
          ./Patrol_algorithm;
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
